// New file keys - PVH CKNA


// New file keys - PVH CK

export const BSKEYS = [
  "FOB Price",	
  "Revised FOB",	
  "Req sail by date",	
  "CFM sail by date",	
  "Factory",	
  "Revised Factory",	
  "Customer Style(Style)",	
  "Style Color(Color)",	
  "FG PO#",	
  "Final Qty",	
  "Prepack Description",	
  "Ship to"
]

export const PSSKEYS = [
  "Name",
  "Gender",	
  "Country",	
  "Region",	
  "Retail PO Vs Wholesale PO",	
  "Season Name",
  "Season Year",	
  "Customer Drop Ship Name",	
  "Issue Date",	
  "Earliest Amendment Date",	
  "Order Status",
  "PO #",
  "Long Description",	
  "Program Name",	
  "Buyer Item #",	
  "Color",	
  "Color Description",	
  "Size",	
  "Quantity",	
  "Customs Units",	
  "Invoice Total Qty",
  "Latest Date",	
  "Unit Of Measure",
  "Unit Price",	
  "Currency",	
  "Qty per Inner Pack",	
  "QTY Per Inner Pack",	
  "Qty per Outer Pack",	
  "Member Name",	
  "Delivery Term",	
  "Fiber Content",
  "Comments 1",	
  "SHIPMENT AUTHORIZATION #",	
  "Retail Cost Price",	
  "Box End Code",	
  "UPC/EAN (GTIN)",	
  "UPC #",	
  "Country	Season",	
  "Season Code",
  "Season Year",	
  "Pack Method",
  "Ship To Code",	
  "Ship Window End Date",	
  "PO Classification Code",	
  "Line Shipment Method",
  "Country",	
  "Final Destination",	
  "Country",	
  "Pts Numbers",	
  "Line #",
]

export const AOBKEYS = [
  "CBU",	
  "Buyer",	
  "Group Tech Class",	
  "Buyer Division Code",	
  "Buyer Division Name",	
  "Style No",	
  "Cust Style No",
  "Item Description",	
  "Product Group",	
  "Style Category",	
  "Season",	
  "Garment Fabrication",
  "Lead Factory",	
  "Prod Warehouse",
	"Min CO Sts",	
  "Max CO Sts",	
  "CO No",	
  "CPO No",	
  "VPO No",
  "Delivery Term",	
  "Shipment Mode",	
  "Color Code",	
  "Color Name",	
  "Z Option",	
  "Destination",	
  "Pack Method",	
  "Schedule No",	
  "MFG Schedule",	
  "Trans Reason",	
  "Req Del date",	
  "Plan Del Date",
  "Max Departure Date - CO",	
  "PCD Date",	
  "FOB Date",	
  "NDC Date",	
  "PED",	
  "MO/MOP",	
  "CO Qty",	
  "MO Qty",	
  "Cum Cut Qty",	
  "Cum Sew In Qty",	
  "Cum Sew In Rej Qty",	
  "Cum SewOut Qty",	
  "Cum Sew Out Rej Qty",	
  "Cum CTN Qty",	
  "Cum CTN Rej Qty",	
  "FG transfer + FG Write-off", 	
  "Remaining Qty",	
  "Allocated Qty",	
  "Pick List Qty",	
  "Delivered Qty",	
  "Invoiced Qty",	
  "Order to shipped %",	
  "Excess/Short Shipped Qty",	
  "FOB Price",	
  "FOB after discount",	
  "SMV",	
  "Planned SAH",	
  "Costing Efficiency",
  "CO Responsible",	
  "CO Create Min Date",	
  "CO Create Max Date",	
  "Order placement date",	
  "Drop Dead Date",	
  "AOQ",
  "Type",	
  "Projection Ref",
]

export const AASKEYS = [
  "AA",	
  "Buy Plan",	
  "Vendor",	
  "Vendor Name",
  "Style",	
  "Program Name",	
  "Color",	
  "NRF Color",	
  "Color Name",	
  "Dimension	Size",	
  "UPC",	
  "Ship to",	
  "Office",	
  "Qty",	
  "Final Qty",	
  "Need By",	
  "In DC Date",	
  "Req Sail By",	
  "Req AC Date",	
  "Cfm Sail By",	
  "Cfm AC Date",	
  "Buy Period",	
  "Prepack Style",	
  "Prepack Color",	
  "Prepack Description",
  "Licensee",	
  "Cost Folio Season",	
  "Comment",	
  "Process Step",	
  "Global Style",	
  "PpP",	
  "Total Pcs",	
  "Plant",	
  "Accepted Surcharge",	
  "Confirm Plant",	
  "Base FOB",	
  "Final FOB",	
  "Reason For Not meeting req sail by",	
  "Brandix Comment",	
  "Region comment",	
  "PO #"
]

// Old file keys
export const OBKEYS = [
  "cbu",
  "Buyer",
  "groupTechClass",
  "buyerDivisionCode",
  "buyerDivisionName",
  "styleNo",
  "custStyleNo",
  "itemDescription",
  "productGroup",
  "styleCategory",
  "season",
  "garmentFabrication",
  "leadFactory",
  "prodWarehouse",
  "minCOSts",
  "maxCOSts",
  "CONo",
  "CPONo",
  "VPONo",
  "deliveryTerm",
  "shipmentMode",
  "colorCode",
  "colorName",
  "zOption",
  "destination",
  "packMethod",
  "scheduleNo",
  "MFGSchedule",
  "transReason",
  "reqDeldate",
  "planDelDate",
  "maxDepartureDateCO",
  "PCDDate",
  "FOBDate",
  "NDCDate",
  "PED",
  "MOMOP",
  "COQty",
  "MOQty",
  "cumCutQty",
  "cumSewInQty",
  "cumSewInRejQty",
  "cumSewOutQty",
  "cumSewOutRejQty",
  "cumCTNQty",
  "cumCTNRejQty",
  "FGTransferFGWriteOff" ,
  "remainingQty",
  "allocatedQty",
  "pickListQty",
  "deliveredQty",
  "invoicedQty",
  "orderToShipped",
  "excessShortShippedQty",
  "FOBPrice",
  "FOBAfterDiscount",
  "SMV",
  "plannedSAH",
  "costingEfficiency",
  "COResponsible",
  "COCreateMinDate",
  "COCreateMaxDate",
  "orderplacementDate",
  "dropDeadDate",
  "AOQ",
  "type",
  "projectionRef",
]

export const OORKEYS = [
  "genericArticle",
  "ZDEPT_NMEDepartmentNME",
  "categoryDescription",
  "vendorCountry",
  "POSeasonCode",
  "Generic Article Text",
  "choiceCode",
  "colorMarketingName",
  "merchPlanID",
  "articlePLMID",
  "POFloorsetDate",
  "subBrandDesc",
  "CPO",
  "SO",
  "POCreateDate",
  "PO",
  "POStatus",
  "buyStrategy",
  "originalMastOwnershipDate",
  "planMASTOwnershipDate",
  "planNDC",
  "modeOfShip",
  "factoryVendor",
  "factoryVendorName",
  "vendorCountry",
  "reasonCode",
  "orderQuantity",
  "totalUnitsShipped",
  "totalRemaining",
]

export const OTRKEYS = [
  "program",
  "customerCode",
  "department",
  "season",
  "ORC",
  "buyStrategy",
  "originalFtySAP",
  "newFtySAP",
  "orderPlaced",
  "flexProto",
  "genericArticle",
  "digitalStyle",
  "VPO",
  "SOCPO",
  "description",
  "color",
  "flexColorCode",
  "digitalColorCode",
  "qty",
  "shippableQty",
  "requestedShipMode",
  "confirmedShipMode",
  "revisedShipMode",
  "floorset",
  "initialBrandRequestedNDCUploadedNDC",
  "OMODOriginalGAC",
  "currentSystemMODGAC",
  "originalNDC",
  "currentSystemNDC",
  "devCalculation",
  "proposedMODGAC",
  "proposedNDC",
  "devProposedCurrentCalculation",
  "callOutY",
  "vendorComments",
  "CMHComments",
  "regionalComments",
  "changeType1",
  "changeType2",
  "changeType3",
  "brand",
  "subCategory",
  "region",
  "LAPO",
  "fabricMill",
  "agreedFabricExMill",
  "revisedFabricExMill",
  "fabricExMillDeviation",
  "reasonForRMDeviation",
  "productionEmlishmentDeviationWeeks"
]

export const SAKEYS = [
  "textbox55",
  "SLevelApproval",
  "TLevelApproval",
  "revisionIndex",
  "adviceNoCode",
  "deliveryNo",
  "productionFactory",
  "destination",
  "buyer",
  "style",
  "itemDescription",
  "division",
  "UORNo",
  "handOverDate",
  "mode",
  "scheduleNo",
  "color",
  "MpoNo",
  "CpoNo",
  "BAFob",
  "factoryFob",
  "factoryCM",
  "totalNetWeight",
  "totalGrossWeight",
  "totalNetNetWeight",
  "noOfPackages",
  "totalCBM",
  "SAQuantity",
  "packageMeasurement",
  "SARemarks",
  "marksAndNos",
  "weightUnit",
  "packageType",
  "packingMethod",
  "unitOfMeasurement",
  "textbox25",
  "textbox29",
  "SLevelApprovalDate",
  "SLevelApprovedBy",
  "TLevelApprovalDate",
  "TLevelApprovedBy",
  "THNo",
  "BLComm",
  "culsterMargin",
  "currentCM",
  "addressNo",
  "factoryFobOld",
  "BAFobOld",
  "fabricComposition",
  "frozenCM",
  "company",
  "companyShortCode",
  "leadFactory",
  "leadFactoryShortCode",
  "merchandiser",
  "paymentTerms",
  "quota",
  "class",
  "actualConsumption",
  "SLevelApproval_1",
  "textbox19",
  "M3InvoiceNo",
  "MASNo",
  "TFinalQty",
  "cancelled",
  "IsManualDAN",
  "originalQty"
]

export const OLRKEYS = [
  "CUSTCODE",
  "CUSTNAME",
  "SHIPTOCODE",
  "SHIPTONAME",
  "SHIPMODE",
  "NDCDATE",
  "SHIPDATE",
  "ORIGINALMOD",
  "NDCWEEK",
  "MODWEEK",
  "OMODWEEK",
  "PLANNEDSHIPSEQ",
  "INCO1",
  "INCO2",
  "DIVISIONCODE",
  "DEPARTMENTCODE",
  "PURCHASERCODE",
  "PURCHASINGGROUP",
  "PURGP_DESC",
  "VPONO",
  "VPODATE",
  "REVDATE",
  "VPOVER",
  "CPO",
  "STATUSCODE",
  "LINENO",
  "GENERICNO",
  "VARIANTNO",
  "TECHPACKNO",
  "MASTSTYLE",
  "MASTSTYLEDESC",
  "CUSTSTYLE",
  "CUSTSTYLEDESC",
  "MASTCOLORCODE",
  "MASTCOLORDESC",
  "MASTSIZECODE",
  "MASTSIZEDESC",
  "CUSTCOLORCODE",
  "CUSTCOLORDESC",
  "CUSTSIZECODE",
  "CUSTSIZEDESC",
  "ORDERQTY",
  "BUYINGCOMMISSION",
  "MIDDLEMANCHARGES",
  "VAT",
  "MISCCHARGE",
  "FACTORYCOST",
  "CUSTOMERARTICLE",
  "ALT_SKU",
  "NEXT_SKU",
  "RETAILPRICE_US",
  "RETAILPRICE_CA",
  "RETAILPRICE_UK",
  "RETAILPRICE_CN",
  "CUSTOMERLINE",
  "REFERENCE",
  "PREPACKCODE",
  "BUYSTRATEGY_CODE",
  "BUYSTRATEGY_DESC",
  "ORDERREASON",
  "SPEEDCODE",
  "SPEEDCODE_DESC",
  "SEASON",
  "FLOORSETDATE",
  "FLOORSETWEEK",
  "FACTORYID",
  "FACTORYNAME",
  "COUNTRYOFORIGIN",
  "CID",
  "RAPIDPONO",
  "REFVPO",
  "SONO",
  "SELLPRICE",
  "PACKAGING",
  "HANDLING",
  "REGULATORY_STATUS",
  "CHINA_DUTIABLE_VALUE",
  "CHINA_PRICE_CUR",
  "CREATEDDATE",
  "ISSUSEDDATE",
]